language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t 271097/react-app -f Dockerfile.dev .

script:
    - docker run -e CI=true 271097/react-app npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-1-573607591379"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY